<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# You would lose your changes when you upgrade your site.
#


include dirname(__FILE__) . '/inc/init.php';
include dirname(__FILE__) . '/inc/inc.php';
?>