<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# You would lose your changes when you upgrade your site. Use php widgets instead.
#

global $sem_options;

$active_layout = apply_filters('active_layout', $sem_options['active_layout']);

# show header
include sem_path . '/header.php';


			# the loop
			
			do_action('before_the_entries');

			if ( have_posts() ) :

				# loop through entries

				while ( have_posts() ) :

					the_post();
					
					$class = join(' ', get_post_class());
					
					echo '<div class="entry' . ( $class ? ( ' ' . $class ) : '' ) . '">' . "\n"
						. '<div class="entry_top"></div>' . "\n";
					
					do_action('the_entry');
					
					echo '<div class="entry_bottom"></div>' . "\n"
						. '</div>' . '<!-- entry -->' . "\n";

				endwhile; # have_posts()

			else :

				# fallback

				do_action('the_404');

			endif; # have_posts()

			do_action('after_the_entries');

# show footer
include sem_path . '/footer.php';
?>