<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# You would lose your changes when you upgrade your site. Use php widgets instead.
#

global $sem_options;

$active_layout = apply_filters('active_layout', $sem_options['active_layout']);

# show header
include sem_path . '/header.php';


			# the loop
			
			sem_panels::display('before_the_entries');

			if ( have_posts() ) :

				# loop through entries

				while ( have_posts() ) :

					the_post();
					
					$class = get_post_class();
					
					echo '<article>'
					    . '<div class="entry' . ( $class ? ( ' ' . implode(' ', $class) ) : '' ) . '">' . "\n"
						. '<div class="entry_top"><div class="hidden"></div></div>' . "\n"
						. '<div class="entry_bg">' . "\n";
					
					sem_panels::display('the_entry');
					
					echo '<div class="spacer"></div>' . "\n"
						. '</div>' . "\n"
						. '<div class="entry_bottom"><div class="hidden"></div></div>' . "\n"
						. '</div>' . '<!-- entry -->' . "\n"
                        . '</article>'  . "\n";

				endwhile; # have_posts()

			else :

				# fallback

				sem_panels::display('the_404');

			endif; # have_posts()

			sem_panels::display('after_the_entries');

# show footer
include sem_path . '/footer.php';
?>