<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# You would lose your changes when you upgrade your site. Use php widgets instead.
#


/*
Template Name: Mono Column
*/

add_filter('active_layout', 'strip_s');

include sem_path . '/index.php';
?>