<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# You would lose your changes when you upgrade your site. Use php widgets instead.
#

/*
Template Name: Mono Column
*/

add_filter('active_layout', array('sem_template', 'strip_sidebars'));

include sem_path . '/index.php';
?>