<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# You would lose your changes when you upgrade your site. Use php widgets instead.
#

# show header
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
<meta name="viewport" content="width=device-width" />
<title><?php
if ( $title = trim(wp_title('&#8211;', false)) ) {
	if ( strpos($title, '&#8211;') === 0 )
		$title = trim(substr($title, strlen('&#8211;')));
	echo $title;
} else {
	bloginfo('description');
}
?></title>
<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
<?php
    do_action('wp_head');
?>
</head>
<body class="<?php echo implode(' ', get_body_class(array('skin', 'custom'))); ?>">
<div style="width: 600px; margin-left: auto; margin-right: auto;">
<?php
sem_panels::display('before_the_entries');

# show posts
if ( have_posts() ) :
	while ( have_posts() ) :
		the_post();

?>
<div class="entry" id="entry-<?php the_ID(); ?>">
<?php
		sem_panels::display('the_entry');
?>
</div>
<?php
	endwhile;
# or fallback
elseif ( is_404() ) :
	sem_panels::display('the_404');
endif;

sem_panels::display('after_the_entries');

# show footer
do_action('wp_footer');
?>
</div>
</body>
</html>