<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# You would lose your changes when you upgrade your site. Use php widgets instead.
#

/*
Template Name: Special Page
*/

include sem_path . '/index.php';
?>